package ir.mums.stufood.ui.theme

import androidx.compose.ui.graphics.Color

// A warm, food-inspired light palette
val md_light_primary = Color(0xFF8B5000)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFFFDCBE)
val md_light_onPrimaryContainer = Color(0xFF2C1600)
val md_light_secondary = Color(0xFF735943)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFFFDCBE)
val md_light_onSecondaryContainer = Color(0xFF291806)
val md_light_tertiary = Color(0xFF5B6235)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFE0E8AF)
val md_light_onTertiaryContainer = Color(0xFF181E00)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFFFF8F4)
val md_light_onBackground = Color(0xFF211A14)
val md_light_surface = Color(0xFFFFF8F4)
val md_light_onSurface = Color(0xFF211A14)
val md_light_surfaceVariant = Color(0xFFF2DFD1)
val md_light_onSurfaceVariant = Color(0xFF514538)
val md_light_outline = Color(0xFF837566)
val md_light_inverseSurface = Color(0xFF372F26)
val md_light_inverseOnSurface = Color(0xFFFEEEE0)
val md_light_inversePrimary = Color(0xFFFFB871)

// Dark palette
val md_dark_primary = Color(0xFFFFB871)
val md_dark_onPrimary = Color(0xFF4A2900)
val md_dark_primaryContainer = Color(0xFF693D00)
val md_dark_onPrimaryContainer = Color(0xFFFFDCBE)
val md_dark_secondary = Color(0xFFE0BFA0)
val md_dark_onSecondary = Color(0xFF402C17)
val md_dark_secondaryContainer = Color(0xFF59422B)
val md_dark_onSecondaryContainer = Color(0xFFFFDCBE)
val md_dark_tertiary = Color(0xFFC4CC95)
val md_dark_onTertiary = Color(0xFF2E330C)
val md_dark_tertiaryContainer = Color(0xFF444A20)
val md_dark_onTertiaryContainer = Color(0xFFE0E8AF)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF19130D)
val md_dark_onBackground = Color(0xFFFEEEE0)
val md_dark_surface = Color(0xFF19130D)
val md_dark_onSurface = Color(0xFFFEEEE0)
val md_dark_surfaceVariant = Color(0xFF514538)
val md_dark_onSurfaceVariant = Color(0xFFD6C3B5)
val md_dark_outline = Color(0xFF9E8E81)
val md_dark_inverseSurface = Color(0xFFFEEEE0)
val md_dark_inverseOnSurface = Color(0xFF372F26)
val md_dark_inversePrimary = Color(0xFF8B5000)
